### ISSUE TITLE
Access to the free challenges

### ISSUE THREAD

**Issue by Inspector-Butters** [codecrafters-io/build-your-own-x#1033]
Hi, I am wondering if at the end of the month, the access to the in progress free challenges will be removed. or will users still have access to complete the challenge ?

**Comment by rohitpaulk** [comment]
Hi there! This if probably better asked in https://forum.codecrafters.io/, since this repository isn't related to the challenges themselves. 

Will answer here anyway: if a challenge is made non-free, your repository will remain intact + you'll be able to read all instructions, you just won't be able to run tests for the paid stages.
