### ISSUE TITLE
Gameboy emulator in Rust

### ISSUE THREAD

**Issue by isRodgef** [codecrafters-io/build-your-own-x#327]
### Main programming language
Rust

### Tutorial title
0dmg

### Tutorial URL
https://jeremybanks.github.io/0dmg/

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Command-Line Tool
* [ ] Database
* [ ] Docker
* [x] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by dizaztor** [comment]
Hey, this is pretty cool, but its navigation system is not. When you finish reading a page (from the log), you'd have to go back the main website again (from the URL bar, since it doesn't have a button to go back the main website) and manually see what the next page is. It should just have a NEXT/PREVIOUS button or something.

**Comment by rohitpaulk** [comment]
Added in https://github.com/codecrafters-io/build-your-own-x/commit/2ca60944c16020f7c95b9217e4c5c3770a8a85fd! Thanks for the submission @isRodgef!
